site_name: DrackThor Edu
site_url: http://localhost
nav:
  - Home: index.md
  - BITI VICA SS25:
    - Virtualization Basics:
      - BITI_VICA_SS25/virtualization_basics/index.md
      - Overview: BITI_VICA_SS25/virtualization_basics/virtualization-0.md
    - Infrastructure as Code:
      - BITI_VICA_SS25/iac_basics/index.md
      - Overview: BITI_VICA_SS25/iac_basics/iac-0.md
    - Container Basics:
      - BITI_VICA_SS25/container_basics/index.md
      - Overview: BITI_VICA_SS25/container_basics/containers-0.md
    - Further Reading: BITI_VICA_SS25/further-reading.md

theme:
  name: material
  features:
    - navigation.footer
    # - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
  # favicon: assets/favicon.png
  font:
    text: Merriweather Sans
    code: Anonymous Pro
  icon:
    logo: material/school
  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: dark mode
    primary: green
    accent: deep purple
  # Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: light mode
    primary: blue
    accent: deep yellow
markdown_extensions:
  # emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # tabs
  - pymdownx.tabbed:
      alternate_style: true
  # admonitions
  - admonition
  - pymdownx.details
  # annotations
  - md_in_html

extra:
  social:
    - icon: material/web
      link: https://drackthor.me
    - icon: material/linkedin
      link: https://linkedin.com/in/drackthor

copyright: Copyright &copy; 2025 Daniel Drack