name: build-edu-website

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - 'main'
      - 'release-*'

  pull_request:
    branches:
      - 'main'
      - 'release-*'
  
defaults:
  run:
    shell: bash
jobs:

  prepare_ci_run:
    name: Build Website
    # Prepare CI Run looks at what has been changed in this commit/PR/... and determines which artifacts should be
    # built afterwards (in other jobs that depend on this one).
    runs-on: ubuntu-20.04
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # need to checkout "all commits" for certain features to work (e.g., get all changed files)

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.17'

      - name: Build CodeLabs
        run: |
          go install github.com/googlecodelabs/tools/claat@latest
          for i in $(ls *.md); do claat export $i; done
        working-directory: ./site/codelabs

      - name: Build Site
        run: |
          npm install
          gulp dist
          rm -f ./dist/codelabs
          cp -r ./codelabs ./dist/
        working-directory: ./site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release-*' }}
        with:
          branch: production # The branch the action should deploy to.
          folder: ./site/dist # The folder the action should deploy.
          target-folder: /

      - name: Install Netlify
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release-*' }}
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release-*' }}
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir ./site/dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --json \
            > deploy_output.json

      - name: Generate URL Preview
        id: url_preview
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release-*' }}
        run: |
          NETLIFY_PREVIEW_URL=$(jq -r '.deploy_url' deploy_output.json)
          echo "NETLIFY_PREVIEW_URL=$NETLIFY_PREVIEW_URL" >> "$GITHUB_OUTPUT"

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Preview URL: ${{ steps.url_preview.outputs.NETLIFY_PREVIEW_URL }}
